### ISSUE TITLE
click on option in game crash for version 1.21

### ISSUE THREAD

**Issue by nuypham** [mrsterner/GuardVillagers#121]
Tested only Fabric API and Guard Villagers (Fabric/Quilt) mods.

Crash log:

[19:26:00] [Datafixer Bootstrap/INFO]:
 226 Datafixer optimizations took 375 milliseconds
[19:26:06] [Render thread/INFO]:
 Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[19:26:06] [Render thread/INFO]:
 Setting user: {MINECRAFT_USERNAME}
[19:26:06] [Render thread/INFO]:
 [Indigo] Registering Indigo renderer!
[19:26:07] [Render thread/INFO]:
 Backend library: LWJGL version 3.3.3-snapshot
[19:26:08] [Render thread/INFO]:
 Reloading ResourceManager: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, guardvillagers, midnightlib
[19:26:08] [Worker-Main-13/INFO]:
 Found unifont_all_no_pua-15.1.05.hex, loading
[19:26:08] [Worker-Main-2/INFO]:
 Found unifont_jp_patch-15.1.05.hex, loading
[19:26:09] [Render thread/WARN]:
 Missing sound for event: minecraft:item.goat_horn.play
[19:26:09] [Render thread/WARN]:
 Missing sound for event: minecraft:entity.goat.screaming.horn_break
[19:26:09] [Render thread/INFO]:
 OpenAL initialized on device OpenAL Soft on VA32AQ (NVIDIA High Definition Audio)
[19:26:09] [Render thread/INFO]:
 Sound engine started
[19:26:10] [Render thread/INFO]:
 Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[19:26:10] [Render thread/INFO]:
 Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[19:26:10] [Render thread/WARN]:
 Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[19:26:14] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:436) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.3.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1310) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
Caused by: java.lang.IllegalAccessError: class net.minecraft.class_429 tried to access private method 'void net.minecraft.class_2960.<init>(java.lang.String, java.lang.String)' (net.minecraft.class_429 and net.minecraft.class_2960 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @675d3402)
	at net.minecraft.class_429.<init>(class_429.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_19863(class_442.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_25402(class_442.java:295) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 14 more

**Comment by ConnorSaysHi** [comment]
I have been having the exact same kind of issue. With the mod installed, if I were to click on 'Options,' then the game immediately crashes. So far, it seems to do it whether it is paired with other mods or not. I look forward to this being patched and appreciate the effort that the devs have put into this project!

**Comment by mrsterner** [comment]
Cool, ill fix it today
