### ISSUE TITLE
Game does not launch in 1.19, even after said fix was implemented

### ISSUE THREAD

**Issue by maybearidan** [mrsterner/GuardVillagers#25]
Game crashes imedienltley after launch, and ends with code -1.  Running the latest version that was released about 3 hours ago,

Crash report:

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2022-07-11 23:04
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'guardvillagers'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    dev/mrsterner/guardvillagers/common/entity/GuardEntity.lambda$initGoals$3(Lnet/minecraft/class_1309;)Z @17: invokevirtual
  Reason:
    Type 'net/minecraft/class_1309' (current frame, stack[1]) is not assignable to 'dev/mrsterner/guardvillagers/common/entity/GuardEntity'
  Current Frame:
    bci: @17
    flags: { }
    locals: { 'net/minecraft/class_1309' }
    stack: { 'java/util/List', 'net/minecraft/class_1309' }
  Bytecode:
    0000000: 2ac1 06a6 9900 1cb2 0314 b403 18b4 06aa
    0000010: 2ab6 06ae b906 af02 009a 0007 04a7 0004
    0000020: 03ac                                   
  Stackmap Table:
    same_frame(@32)
    same_locals_1_stack_item_frame(@33,Integer)

	at dev.mrsterner.guardvillagers.GuardVillagers.<clinit>(GuardVillagers.java:44)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:443)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Bibliotek för användargränssnittskontroller:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:32-bitars kryptografi-API:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DLL-fil med API för DNS-klient:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Klient-DLL för Windows NT BASE API:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Klient-DLL för Windows NT BASE API:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE för Windows:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Körning av RPC (Remote Procedure Call):10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:DLL-fil för Windows-gränssnittet:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		SspiCli.dll:Security Support Provider Interface:10.0.22000.556 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Fleranvändarklient-DLL-fil för Windows:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:DLL-filen för Windows Socket 2.0 32-Bit:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22000.593 (WinBuild.160101.0800):Microsoft Corporation
		antimalware_provider64.dll:AMSI provider :
```

**Comment by IgnitedDragon** [comment]
I've been having the same exact problem

**Comment by mrsterner** [comment]
I be darnd, hard to fix when i cant recreate, ill try again after work

**Comment by mrsterner** [comment]
Found the error, will fix when i get home

**Comment by JairusSW** [comment]
@mrsterner, will the 1.19.1 version work for 1.19?

**Comment by maybearidan** [comment]
The 1.19.1 version works with 1.19, yes.
