### ISSUE TITLE
Server crashing on player logout 

### ISSUE THREAD

**Issue by Susslord** [mrsterner/GuardVillagers#50]
I'm getting a crash on my server, it started right after I duplicated my atlas to share with other players. Often it happens when someone logs off who has an atlas. The whole server goes down, and it seems only to happen if there's more than one player online. I don't get the crash just on my own.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-12-30 08:03:20
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
	at pepjebs.mapatlases.lifecycle.MapAtlasesServerLifecycleEvents.mapAtlasServerTick(MapAtlasesServerLifecycleEvents.java:151)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$0(ServerTickEvents.java:40)
	at net.minecraft.server.MinecraftServer.handler$bcb000$onStartTick(MinecraftServer.java:3816)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 3.10.0-1160.11.1.el7.x86_64
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1796399216 bytes (1713 MiB) / 3145728000 bytes (3000 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 68432.50
	Virtual memory used (MB): 110035.56
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 74.00
	JVM Flags: 20 total; -Xms256M -Xmx6144M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		adventurez: AdventureZ 1.4.17
		another_furniture: Another Furniture 2.1.2-1.19.2
		apollo: Apollo's Additional Structures 1.3.1
		architectury: Architectury 6.4.62
		attributefix: AttributeFix 17.1.2
		axesareweapons: Axes Are Weapons 1.6.0
		bettercombat: Better Combat 1.5.3+1.19
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterenchantmentboosting: Better Enchantment Boosting 1.2.1
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		bettertridents: Better Tridents 4.0.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.6-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		bottleyourxp-fabric: Bottle Your Xp (Fabric) 2.2
		boundweapons: Boundweapons 1.0.2-1.19.2
		bushierflowers: Bushier Flowers 0.0.1-1.19.2
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		chimes: Chimes 1.1.4
		cloth-api: Cloth API 4.0.65
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		collective-fabric: Collective (Fabric) 5.22
			fiber: fiber 0.23.0-2
		combit: ComBit 1.1.4
		comforts: Comforts 6.0.3+1.19.2
			spectrelib: SpectreLib 0.10.0+1.19
		companion: Companion 3.1.2
		continents: Continents 1.1
		convenientnametags: Convenient Name Tags 0.2.0
		copper_golem: Copper Golem 1.4.0
		craftablechainmail: Craftable Chainmail Armor 1.19.2-1.6.3-[FABRIC]
		craftycuisine: Crafty Cuisine 1.2.0
		cursery: Cursery Mod 1.19.2-3.1
		dataattributes: Data Attributes 1.2.8
		despawningeggshatch-fabric: Despawning Eggs Hatch (Fabric) 2.9
		dragonfight: Dragonfight Mod 1.19.2-2.6
		dtdash: Double-Tap Dash 1.2.1-1.19
		dummmmmmy: MmmMmmMmmMmm 1.19-1.5.3
		dungeon_difficulty: Dungeon Difficulty 1.2.1+1.19
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.1.1
		ecologics: Ecologics 2.1.11
		eldritch_mobs: EldritchMobs 1.12.10
			polymer: Polymer (Core) 0.2.18+1.19.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			polymer-blocks-ext: Polymer Blocks 0.1.0-alpha.9+1.19.2
			server_translations_api: Server Translations API 1.4.18+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		elytraslot: Elytra Slot 6.0.0+1.19.2
		emi: EMI 0.5.3+1.19.2
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		exlinecopperequipment: Copper Equipment 2.1.2
		explorify-fabric: Explorify 1.19-1.3.0
		extended_armor_bars: Extended Armor Bars 1.2.1
		extraalchemy: Extra Alchemy 1.9.0
		fabric-api: Fabric API 0.69.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.4+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.3+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.36+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.10+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.13+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.21+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.3+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.2+574a764890
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricenchantments: Fabric Enchantments 0.9.0
		fabricloader: Fabric Loader 0.14.12
		forgeconfigapiport: Forge Config API Port 4.2.9
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		frostiful: Frostiful 0.2.6
			mm: Manningham Mills 2.3
		frycmobvariants: Mob Variants 1.0.2+1.19.2
		frycparry: Sword Parry 1.0.4+1.19.2-3
		geckolib3: Geckolib 3.1.38
			com_eliotlash_mclib_mclib: mclib 20
		guardvillagers: Guard Villagers Fabric 1.19.2-1.0.16
		herdspanic: Herds Panic 1.0.6
		hopobettermineshaft: Hopo Better Mineshaft 1.1.5
		incendium: Incendium 5.1.4
		java: Java HotSpot(TM) 64-Bit Server VM 17
		libjf: LibJF 3.2.1
			libjf-base: LibJF Base 3.2.1
			libjf-config-commands-v1: LibJF Config Commands 3.2.1
			libjf-config-core-v1: LibJF Config 3.2.1
			libjf-config-legacy-shim: LibJF Config Legacy Shim 3.2.1
			libjf-config-reflect-v1: LibJF Config Reflect 3.2.1
			libjf-data-manipulation-v0: LibJF Data Manipulation 3.2.1
			libjf-data-v0: LibJF Data 3.2.1
			libjf-translate-v1: LibJF Translate 3.2.1
			libjf-unsafe-v0: LibJF Unsafe 3.2.1
			libjf-web-v0: LibJF Web 3.2.1
		linearxp: Linear XP 1.0.1
		lithium: Lithium 0.10.4
		logprot: Logprot Mod 1.19-1.9
		lootr: Lootr 0.4.25.64
		loud_leads: Loud Leads 1.0.1+mc1.19
		map_atlases: Map Atlases 2.3.0
		megaparrot: Megaparrot 1.0.7-1.19.2
		midnightlib: MidnightLib 1.0.0
		minecarttweaks: Cammie's Minecart Tweaks 1.7
		minecraft: Minecraft 1.19.2
		mixintrace: MixinTrace 1.1.1+1.17
		naturalist: Naturalist 2.1.1
		noenchantcap: No Enchant Cap 2.2.4
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		notenoughbreeding: Not Enough Breeding 1.19.2-1.0.0-fabric
		nullscape: Nullscape 1.2
		peacefulsurface: PeacefulSurface 1.19.2-v1-fabric
		perfectaccuracy: Perfect Accuracy 1.2-1.19
		perplayerspawns: Example Mod 3.0.3
		phantomredux: Phantom Redux 1.0.0+all-versions+fabric
		philipsruins: Philip`s ruins 1.19.2
		pickyourpoison: Pick Your Poison 1.0.11
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			org_json_json: json 20211205
		player-animator: Player Animator 0.4.0
		playerex: PlayerEx 3.3.8
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.6.4
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
		potionload: Potion Load Mod 1.1-1.19
		precise_armor: Precise Armor 1.0
		progressivebosses: Progressive Bosses 1.0.0
			completeconfig-base: completeconfig-base 2.0.1
		projectile_damage: Projectile Damage Attribute 3.0.0+1.19
		puzzleslib: Puzzles Lib 4.3.12
		realisticsleep: Realistic Sleep 1.6.0
		relicex: RelicEx 3.2.6
			armorrenderlib: Armor Render Lib 0.2.6
		revive: Revive 1.0.5
		skylorlib: SkyLib 1.5.1
		smallships: Small Ships 2.0.0a1.1.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		smwyg: Show Me What You Got 1.0.3
		snowyleavesplus: SnowyLeavesPlus 0.1.4
		soulfired: Soul fire'd 1.1.0.0
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		spiderstpo: Spiders 2.0 1.19.2-2.0.3
		structory: Structory 1.0.1
		takesapillage: Takes a Pillage 1.0.4
		themissingvillages: BigReefer's The Missing Villages Mod 2.0.0
		treechop: HT's TreeChop 0.17.0
		trinkets: Trinkets 3.4.1
		variablespawnerhardness: Variable Spawner Hardness 1.19.2-1.2.2
		variant_bookshelves: Variant Bookshelves 1.2.4
		variantbarrels: Variant Barrels 2.4.5
		variantcraftingtables: Variant Crafting Tables 3.2.9
		villager-hats: Villager Hats 1.4.1
		vtaw_mw: Variant Tools and Weaponry - Extra Weapons 1.0.0
		walllanterns: Lanterns Belong on Walls 1.4.0-1.19
		wandering_collector: Wandering Collector 1.1.3+mc1.19
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
		zombiehorsespawn-fabric: Zombie Horse Spawn (Fabric) 3.6
	Server Running: true
	Player Count: 1 / 60; [class_3222['Chahke'/545, l='ServerLevel[HibisWorld]', x=-5273.50, y=63.22, z=-403.50]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Susslord** [comment]
I had some more crashes, it doesn't seem to happen all the time, only with some players. and regardless of if they've manually opened the map as well. I still need to test if it's something to do with having the map in their trinket slot on log off. It also might have something to do with the version of my modpack player's are using as it seems to have happened with only players that have manually installed my newest version. However they should have a one to one duplicate of what i'm personally running, so I don't see why they'd cause a crash and I don't. I'll do some more testing and upload crash reports.

[crash-2022-12-30_12.39.43-server.txt](https://github.com/mrsterner/GuardVillagers/files/10324800/crash-2022-12-30_12.39.43-server.txt)

**Comment by Susslord** [comment]
Sorry this got missposted to this github.
