### ISSUE TITLE
Mod crashes game any time a Guard Villager loads :(

### ISSUE THREAD

**Issue by TeamYKZA** [mrsterner/GuardVillagers#76]
The crash report is as follows, I hope this could be fixed:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-07-23 14:42:26
Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/class_5601
	at dev.sterner.GuardVillagersClient.<clinit>(GuardVillagersClient.java:25)
	at dev.sterner.common.entity.GuardEntity.method_5994(GuardEntity.java:181)
	at net.minecraft.class_1308.method_5966(class_1308.java:276)
	at net.minecraft.class_1308.method_5670(class_1308.java:289)
	at net.minecraft.class_1297.method_5773(class_1297.java:474)
	at net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at dev.sterner.common.entity.GuardEntity.method_5773(GuardEntity.java:447)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5601
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dev.sterner.GuardVillagersClient.<clinit>(GuardVillagersClient.java:25)
	at dev.sterner.common.entity.GuardEntity.method_5994(GuardEntity.java:181)
	at net.minecraft.class_1308.method_5966(class_1308.java:276)
	at net.minecraft.class_1308.method_5670(class_1308.java:289)
	at net.minecraft.class_1297.method_5773(class_1297.java:474)
	at net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at dev.sterner.common.entity.GuardEntity.method_5773(GuardEntity.java:447)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: guardvillagers:guard (dev.sterner.common.entity.GuardEntity)
	Entity ID: 97259
	Entity Name: Guard
	Entity's Exact location: 5568.45, 73.77, 3902.56
	Entity's Block location: World: (5568,73,3902), Section: (at 0,9,14 in 348,4,243; chunk contains blocks 5568,-64,3888 to 5583,319,3903), Region: (10,7; contains chunks 320,224 to 351,255, blocks 5120,-64,3584 to 5631,319,4095)
	Entity's Momentum: 0.00, -0.23, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Bean_Soup'/3415, l='ServerWorld minecraft:overworld world', x=5661.77, y=62.07, z=3601.46]]
	Chunk stats: 13399
	Level dimension: minecraft:overworld
	Level spawn location: World: (5628,83,-760), Section: (at 12,3,8 in 351,5,-48; chunk contains blocks 5616,-64,-768 to 5631,319,-753), Region: (10,-2; contains chunks 320,-64 to 351,-33, blocks 5120,-64,-1024 to 5631,319,-513)
	Level time: 10306544 game time, 723001 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 35507 (now: false), thunder time: 4349 (now: true)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.4.0-137-generic
	Java Version: 18, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1033913048 bytes (986 MiB) / 11182014464 bytes (10664 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: ASPEED Graphics Family
	Graphics card #0 vendor: ASPEED Technology, Inc. (0x1a03)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x2000
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16033.20
	Virtual memory used (MB): 11796.85
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx16384m
	Fabric Mods: 
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.10
		biomemakeover: Biome Makeover 1.20.1-1.10.2
			taniwha: Taniwha 1.20.0-5.1.1
		bot: Base Origins Tweaks 1.0.0
		cristellib: Cristel Lib 1.1.1
			blue_endless_jankson: jankson 1.2.1
		ctov: ChoiceTheorem's Overhauled Village 3.3.2
		dungeons_arise: When Dungeons Arise 2.1.56.1
		elytratrims: Elytra Trims 1.1.9
			conditional-mixin: conditional mixin 0.3.2
		fabric-api: Fabric API 0.85.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.8+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.12+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.8+40e50c4677
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.38+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.42+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.48+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.0+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.8+e3d6ed2577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.3+43a3fedd77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabricloader: Fabric Loader 0.14.21
		geckolib: Geckolib 4.2.1
			com_eliotlash_mclib_mclib: mclib 20
		guardvillagers: GuardVillagers 2.0.3-1.20.1
			midnightlib: MidnightLib 1.4.1
			porting_lib_base: Porting Lib Base 2.1.1070+1.20
				mm_shedaniel: Manningham Mills (shedaniel's fork) 2.4.1
				porting_lib_accessors: Porting Lib Accessors 2.1.1070+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1070+1.20
				porting_lib_fake_players: Porting Lib Fake Players 2.1.1070+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1070+1.20
				porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_transfer: Porting Lib Transfer 2.1.1070+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1070+1.20
			porting_lib_common: Porting Lib Common 2.1.1070+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1070+1.20
				porting_lib_core: Porting Lib Core 2.1.1070+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1070+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1070+1.20
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1070+1.20
		hwr: Water Resistance Potion 1.0.0+1.20.1
		immersive_portals: Immersive Portals 3.1.2
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
			dimension_data_fix: Dimension Data Fix 2.0.0
			imm_ptl_core: Immersive Portals Core 3.1.2
			q_misc_util: QMiscUtil 3.1.2
		incendium: Incendium 5.3.0
		java: OpenJDK 64-Bit Server VM 18
		minecraft: Minecraft 1.20.1
		nullscape: Nullscape 1.2.1
		orb: Orb of Origin Plus 1.0.0
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				additionalentityattributes: Additional Entity Attributes 1.3.0+1.20.0
				calio: Calio 1.11.0
				cardinal-components-base: Cardinal Components API (base) 5.2.1
				cardinal-components-entity: Cardinal Components API (entities) 5.2.1
				playerabilitylib: Pal 1.8.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		persistent-pearls: Persistent Pearls 1.0.2
		riverredux: River Redux 0.3.1
		simply_houses: Simply Houses 1.1.4-1.20.1
		t_and_t: Towns and Towers 1.10.2
		terrablender: TerraBlender 3.0.0.169
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		terralith: Terralith 2.4.2
		toomanyorigins: TooManyOrigins 0.9.1+1.20.1-fabric
			apugli: Apugli 2.4.4+1.20.1-fabric
		totem-anywhere: Totem Anywhere 1.1.4+1.19.2
	Server Running: true
	Player Count: 1 / 300; [class_3222['Bean_Soup'/3415, l='ServerWorld minecraft:overworld world', x=5661.77, y=62.07, z=3601.46]]
	Data Packs: vanilla, fabric, file/VanillaTweaks_c131944_MC1.20.x.zip, file/any-weather-channeling-v2-1-1.zip (incompatible), file/armor statues v2.8.5 (MC 1.20.x).zip, file/armored elytra v1.0.7 (MC 1.20.x).zip, file/cauldron concrete v2.0.7 (MC 1.20.x).zip, file/custom nether portals v2.3.7 (MC 1.20.x).zip, file/double shulker shells v1.3.4 (MC 1.20.x).zip, file/dragon drops v1.3.4 (MC 1.20.x).zip, file/fast leaf decay v2.0.7 (MC 1.20.x).zip, file/graves v2.8.8 (MC 1.20.x).zip, file/pk-racks-v-2-2-0.zip, file/player head drops v1.1.4 (MC 1.20.x).zip, file/spectator night vision v1.1.4 (MC 1.20.x).zip, file/timber_v2.1.6_(MC_1.20.x)[1].zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by mrsterner** [comment]
Well this doesn't make an ounce of sense, ill check it out when i get home from work
