### ISSUE TITLE
Crash on Map load 1.20.1

### ISSUE THREAD

**Issue by Tipus4u** [mrsterner/GuardVillagers#88]
Below is the crash report.
Testing the 1.20.1 version before changing server from 1.19.4 with the same mods.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-08-25 16:04:13
Description: Exception ticking world

java.lang.NoClassDefFoundError: dev/mrsterner/guardvillagers/common/entity/GuardEntity
	at io.github.overlordsiii.villagernames.integration.villagerguards.VillagerGuardsIntegration.createGuardVillagerNames(VillagerGuardsIntegration.java:17)
	at io.github.overlordsiii.villagernames.VillagerNames.lambda$onInitialize$1(VillagerNames.java:95)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:39)
	at net.minecraft.class_3218$class_5526.handler$baf000$fabric-lifecycle-events-v1$invokeEntityLoadEvent(class_3218.java:1696)
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1577)
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1536)
	at net.minecraft.class_5579.method_31847(class_5579.java:216)
	at net.minecraft.class_5579.method_31820(class_5579.java:186)
	at net.minecraft.class_5579.method_31818(class_5579.java:167)
	at net.minecraft.class_3218.method_14175(class_3218.java:911)
	at net.minecraft.class_3218.method_8649(class_3218.java:862)
	at net.minecraft.class_2248.method_36993(class_2248.java:393)
	at net.minecraft.class_2248.method_9577(class_2248.java:364)
	at net.minecraft.class_2248.method_9544(class_2248.java:352)
	at it.unimi.dsi.fastutil.objects.ObjectArrayList.forEach(ObjectArrayList.java:748)
	at net.minecraft.class_2248.method_9511(class_2248.java:352)
	at net.minecraft.class_1937.method_30093(class_1937.java:306)
	at net.minecraft.class_1945.method_8651(class_1945.java:27)
	at net.minecraft.class_1945.method_22352(class_1945.java:22)
	at net.minecraft.class_4863.method_9588(class_4863.java:57)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1113)
	at net.minecraft.class_3218.method_14189(class_3218.java:728)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:323)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: dev.mrsterner.guardvillagers.common.entity.GuardEntity
	... 31 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.overlordsiii.villagernames.integration.villagerguards.VillagerGuardsIntegration.createGuardVillagerNames(VillagerGuardsIntegration.java:17)
	at io.github.overlordsiii.villagernames.VillagerNames.lambda$onInitialize$1(VillagerNames.java:95)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:39)
	at net.minecraft.class_3218$class_5526.handler$baf000$fabric-lifecycle-events-v1$invokeEntityLoadEvent(class_3218.java:1696)
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1577)
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1536)
	at net.minecraft.class_5579.method_31847(class_5579.java:216)
	at net.minecraft.class_5579.method_31820(class_5579.java:186)
	at net.minecraft.class_5579.method_31818(class_5579.java:167)
	at net.minecraft.class_3218.method_14175(class_3218.java:911)
	at net.minecraft.class_3218.method_8649(class_3218.java:862)
	at net.minecraft.class_2248.method_36993(class_2248.java:393)
	at net.minecraft.class_2248.method_9577(class_2248.java:364)
	at net.minecraft.class_2248.method_9544(class_2248.java:352)
	at it.unimi.dsi.fastutil.objects.ObjectArrayList.forEach(ObjectArrayList.java:748)
	at net.minecraft.class_2248.method_9511(class_2248.java:352)
	at net.minecraft.class_1937.method_30093(class_1937.java:306)
	at net.minecraft.class_1945.method_8651(class_1945.java:27)
	at net.minecraft.class_1945.method_22352(class_1945.java:22)
	at net.minecraft.class_4863.method_9588(class_4863.java:57)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1113)
	at net.minecraft.class_3218.method_14189(class_3218.java:728)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:323)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (-96,108,-112), Section: (at 0,12,0 in -6,6,-7; chunk contains blocks -96,-64,-112 to -81,319,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 4 game time, 4 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 45971 (now: false), thunder time: 135496 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1955009232 bytes (1864 MiB) / 4966055936 bytes (4736 MiB) up to 35869687808 bytes (34208 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) HD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5912
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8854
	Graphics card #1 name: NVIDIA GeForce GTX 1050
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1c81
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3667
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.40
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37495.09
	Virtual memory used (MB): 14814.59
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx34208m -Xms256m
	Fabric Mods: 
		adorn: Adorn 5.0.0+1.20.1
		architectury: Architectury 9.1.12
		areas: Areas 5.0
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		clutter: Clutter 1.20-0.4.3
		collective: Collective 6.65
		controlling: Controlling For Fabric 12.0.2
		ctov: ChoiceTheorem's Overhauled Village 3.3.3
		doubledoors: Double Doors 5.0
		exlinefurniture: Exline's Furniture 2.6.3
		fabric-api: Fabric API 0.87.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.2+6bdb2ed077
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.2+6bdb2ed077
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.9+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.22
		geckolib: Geckolib 4.2.2
			com_eliotlash_mclib_mclib: mclib 20
		globalpacks: Global Data- & Resourcepacks 1.16.1_fabric
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		guardvillagers: GuardVillagers 2.0.7-1.20.1
			porting_lib_base: Porting Lib Base 2.1.1070+1.20
				mm_shedaniel: Manningham Mills (shedaniel's fork) 2.4.1
				porting_lib_accessors: Porting Lib Accessors 2.1.1070+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1070+1.20
				porting_lib_fake_players: Porting Lib Fake Players 2.1.1070+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1070+1.20
				porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_transfer: Porting Lib Transfer 2.1.1070+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1070+1.20
			porting_lib_common: Porting Lib Common 2.1.1070+1.20
				com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
				porting_lib_core: Porting Lib Core 2.1.1070+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1070+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1070+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1070+1.20
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1070+1.20
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.27
		mcwbridges: Macaw's Bridges 2.1.0
		mcwdoors: Macaw's Doors 1.1.0
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwlights: Macaw's Lights and Lamps 1.0.6
		mcwpaintings: Macaw's Paintings 1.0.0
		mcwpaths: Macaw's Paths and Pavings 1.0.3
		mcwroofs: Macaw's Roofs 2.2.4
		mcwtrpdoors: Macaw's Trapdoors 1.1.1
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.1
		moonlight: Moonlight 1.20-2.8.7
		mvs: Moog's Voyager Structures 4.0-1.20-fabric
		plutoscoffee: Pluto's Coffee Mod 1.20.1-2.1
		randomvillagenames: Random Village Names 3.3
		regrowth: Regrowth 83.31.1
		searchables: Searchables 1.0.1
		simplehudenhanced: Simple Hud Enhanced v3.1.0
		simply_houses: Simply Houses 1.1.4-1.20.1
		smarterfarmers: Smarter Farmers 1.20-1.7.3
		villagernames: Villager Names 4.5.2
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-level: Cardinal Components API (world saves) 5.2.1
		villagersplus: Villagers Plus 2.1
		waig: Where Am I Going 1.1.5
		wildfire_gender: Wildfire's Female Gender Mod 1.20-3.0.1
		xaerominimapfair: Xaero's Minimap 23.4.4
		xaeroworldmap: Xaero's World Map 1.33.1
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.22-1.20.1

**Comment by mrsterner** [comment]
Issue with the villager names mod

**Comment by dopemike** [comment]
@mrsterner, will you try to make it compatible with villager names mod? I would love to use both
